"""

Revision ID: 3239cbfcd8cb
Revises:
Create Date: 2023-12-23 18:34:51.369655

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3239cbfcd8cb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('parcel_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('session_id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('parcel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('parcel_type_id', sa.Integer(), nullable=False),
    sa.Column('content_value', sa.Float(), nullable=True),
    sa.Column('user_session_id', sa.String(length=50), nullable=True),
    sa.Column('delivery_cost', sa.Float(), nullable=True),
    sa.Column('delivery_company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['parcel_type_id'], ['parcel_types.id'], ),
    sa.ForeignKeyConstraint(['user_session_id'], ['user.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parcel')
    op.drop_table('user')
    op.drop_table('parcel_types')
    op.drop_table('companies')
    # ### end Alembic commands ###
